### ISSUE TITLE
Faulty process detection is costing me remote access

### ISSUE THREAD

**Issue by working-name** [safing/portmaster#1121]
### What happened?
Ran portmaster, allowed Rustdesk all connections, incoming and outgoing. Portmaster put the connection attempts into &#34;Other Connections&#34; and sometimes &#34;Network noise&#34;.

### What did you expect to happen?
Don&#39;t block rustdesk connections.

### How did you reproduce it?
Install portmaster. Install rustdesk. Run it for a while, working. Update portmaster, watch it go ballistic after its self restart where it can&#39;t figure out who its mother is. Random IPs all over, doesn&#39;t resolve a thing, misrepresents the connection&#39;s process. Basically locks you out of your own computer if you&#39;re remoting in.

Rebooting windows doesn't help.

### Additional information

**Debug-Info**: https://support.safing.io/privatebin/?6d20c0b0425e1d58#4EEuAjCXwusk5QrMAQeksRSMdSk9t3wGJmygvaDGc2jc

**Comment by working-name** [comment]
![bad-process-identification](https://user-images.githubusercontent.com/16505052/222941087-5aab7382-6e77-41c6-8d7c-3c0c7366c889.png)
Another example, the process initiating that connection would be brave.exe not 1password.

**Comment by working-name** [comment]
![why](https://user-images.githubusercontent.com/16505052/222941197-23174b0e-4f9b-46be-9f38-e6dc2ad2fe98.png)
Wrong again, that would have been an email client.

**Comment by working-name** [comment]
@dhaavi No, it's just poor process detection on portmaster's side. I cannot find PID recycling, what I find are old, non-running PIDs assigned to random apps. I can't find rhyme or reason here because there's too many confounding factors:
- PID listed for app X in PM does not exist or belongs to app Y currently running
- connection attempts assigned to app X are unexpected (i.e. app X does not need to access imap.gmail.com)
- some other random app Z gets part of the connection attempts that should really be made by an email client (i.e. smtp.gmail.com)

This happens consistently on 2 separate systems, both Windows 11 however.

So I can't help here. Good luck!

**Comment by dhaavi** [comment]
Well, Windows tells us the PID of the connection via the `iphlpapi.dll`, there is only so much we can do wrong, and this has been running great for the last 4 years now.

We've had single reports of wrong attribution the last couple months, but I do feel these issues are increasing. This might be due to an issue in Windows itself, introduced in a recent update, or just my perception due to increased adoption of Portmaster.

However, this is why I don't think that the process detection itself is faulty, rather some bug later in the process, eg. by having outdated caches and using old data, which of course means that whatever wrong application is displayed, it must have had a network connection in the past.

If Portmaster shows an application that never connections to the Internet, then it's really easy, as this can only be Windows' fault, as it provided that PID.

So, current thesis is:
- Portmaster sees connection and gets the process with PID 100
- All connections end and the process dies, but Portmaster needs to keep the data around for a while to show it in the UI.
- Before Portmaster removes the process with PID 100 from its internal state, a new process with PID 100 shows up and makes a connection.
- Portmaster asks Windows for the PID and sees it already loaded the process for PID 100, but the cache is outdated at that point and the wrong process is attributed.

How does the data look like to support this thesis?
pro:
- General feeling of what is going on
- This instance: https://github.com/safing/portmaster/issues/1138#issuecomment-1476445320
  - Although it is unknown why task manager would initiate that connection
  - But this would mean there are two issues present at the same time
contra:
- Apparently, happening less than 10 min after restart, where caches are empty or should not be outdated.

One thing I saw in a couple screenshots here: Do you use prompting on all occasions when this happens?

**Comment by working-name** [comment]
I follow what you're saying, and it may be plausible, but if the bug is a new update to windows, then they pushed it to windows 10 as well, as another user reported wrong exe detection on that version as well.

Yes, I use Prompt as the default action on both Windows installations.

**Comment by working-name** [comment]
I don't know how to change matching criteria, didn't think that was an option. So I'm using the default profiles created by PM.

**Comment by dhaavi** [comment]
Okay.

I just realized that we have debug endpoint to get more info on the network state.

Please enable the [Development Mode](https://docs.safing.io/portmaster/settings#core/devMode) and when a connection is attributed to the wrong process the next time, please:
- Get connection data by clicking "Copy JSON" from the expanded connection.
- [Get Network State Table Data](https://docs.safing.io/portmaster/api#v1/debug/network/state) by opening http://127.0.0.1:817/api/v1/debug/network/state in your browser.
- Then, paste both of them into our private bin (https://support.safing.io/privatebin/) and provide us the link. (Privately, if you prefer.)

**Comment by dhaavi** [comment]
We have just released a fix for this to Beta in Portmaster v1.0.11. Please check if that also solves the issue for you.

**Comment by ProphetAlgorithms** [comment]
I think I have the same problem with the star citizen game, with version 1.0.11 the situation has improved because in the profile of the app it displays all the connections  detects (with the previous version it reported 6 out of 13, now 13 out of 13), but still there are connections that concern this game (like dns requests) in the "other connections" section. The result is that the game crashes while trying to login and issues an error.

**Comment by working-name** [comment]
@dhaavi it does not - I still see connections to zoom.us and discord under other connections. Software still takes a LONG LONG time to do its thing because PM responds very slowly - nothing shows up in the connection log nor in the prompts (I keep it on Prompt by default) for a good minute or more. Then I finally see both denied connection in the log and prompts for the same denied connections. This means if I have PM installed and active I'm actively wasting my time and doing nothing for my privacy.

I tried resetting DNS cache, restarting, and so on. Using 1.0.12 by the way since I don't have a way to pick my version or download a specific one.

**Comment by working-name** [comment]
Still an issue in 1.0.13 beta release. Same as above, other connections.

**Comment by working-name** [comment]
Closing as portmaster is now interested in charging for broken and incomplete features. I do not support this.
