### ISSUE TITLE
No version number reported in windows

### ISSUE THREAD

**Issue by leochras** [safing/portmaster#503]
**What happened**:

The most recent version of the portmaster installer still doesn't report the version number to windows:

![image](https://user-images.githubusercontent.com/16163571/151131223-8d2fc7bb-02f7-4bb0-8071-7af10ad2bf4d.png)

**What did you expect to happen?**:

The installer should report the version of portmaster to windows.
This would make upgrades with winget possible. As of now, it only says  that the version is "unknown" and this makes upgrading impossible. 

![image](https://user-images.githubusercontent.com/16163571/151132463-8e339a48-cd14-4df2-8b16-8ae694d3581a.png)

**How did you reproduce it?**:

1. Install the most recent version (0.7.14)
2. Go to Apps and Features
3. Search for Portmaster
4. See that there's no version number

**Debug Information**:

<details>
<summary>Version 0.7.14</summary>

```
Portmaster
version 0.7.14

commit tags/v0.7.14-0-gca4bac3b1ba7a88306743012b0960fc69b95d3cc
built with go1.15.8 (gc) windows/amd64
  using options main.go
  by user@docker
  on 23.12.2021

Licensed under the AGPLv3 license.
The source code is available here: https://github.com/safing/portmaster
```

</details>

<details>
<summary>Platform: Microsoft Windows 11 Pro 10.0.22000 Build 22000</summary>

```
System: Microsoft Windows 11 Pro windows (Standalone Workstation) 10.0.22000 Build 22000
Kernel: 10.0.22000 Build 22000 x86_64

```

</details>

<details>
<summary>Status: Trusted</summary>

```
ActiveSecurityLevel:   Trusted
SelectedSecurityLevel: Off
ThreatMitigationLevel: Trusted
CaptivePortal:         
OnlineStatus:          Online
```

</details>

<details>
<summary>Resolvers: 2/2</summary>

```
Cloudflare
  dot://1.1.1.2:853#config
  Failing: false

193.170.137.100
  dns://193.170.137.100:53#system
  Failing: false
```

</details>

<details>
<summary>No Module Error</summary>

</details>

<details>
<summary>Unexpected Logs</summary>

```
220126 09:45:04.062 pat/module:083 > ERRO 509 compat: self-check #2: dns integration check failed: did not receive test query after 3s
220126 09:45:07.504 nameserver:265 > WARN 540 nameserver: failed to resolve wpad.-----.A: all 2 query-compliant resolvers failed, last error: read udp 10.151.68.174:26938->193.170.137.100:53: i/o timeout
220126 09:45:07.504 nameserver:265 > WARN 542 nameserver: failed to resolve _ldap._tcp.dc._msdcs.-----.at.SRV: all 2 query-compliant resolvers failed, last error: read udp 10.151.68.174:37073->193.170.137.100:53: i/o timeout
220126 09:45:08.061 nameserver:265 > WARN 582 nameserver: failed to resolve self.events.data.microsoft.com.A: all 2 query-compliant resolvers failed, last error: read udp 10.151.68.174:37972->193.170.137.100:53: i/o timeout
220126 09:45:10.502 nameserver:265 > WARN 700 nameserver: failed to resolve wpad.------: all 2 query-compliant resolvers failed, last error: read udp 10.151.68.174:63137->193.170.137.100:53: i/o timeout
220126 09:45:19.717 solver-tcp:420 > WARN 980 resolver: read error from Cloudflare (dot://1.1.1.2:853#config): read tcp 10.151.68.174:33605->1.1.1.2:853: wsarecv: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.
220126 09:45:25.561 le/profile:507 > WARN 134 profile: error while getting binary name for C:\Windows\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\SearchHost.exe: failed to get file properties of C:\Windows\SystemApps\MicrosoftWindows.Client.CBS_cw5n1h2txyewy\SearchHost.exe: command succeeded with empty output
220126 09:45:32.048 le/profile:507 > WARN 494 profile: error while getting binary name for C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartMenuExperienceHost.exe: failed to get file properties of C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartMenuExperienceHost.exe: command succeeded with empty output
220126 09:45:32.078 le/profile:507 > WARN 496 profile: error while getting binary name for C:\Windows\System32\DriverStore\FileRepository\nvhm.inf_amd64_d745ea92fee8ab77\Display.NvContainer\NVDisplay.Container.exe: failed to get file properties of C:\Windows\System32\DriverStore\FileRepository\nvhm.inf_amd64_d745ea92fee8ab77\Display.NvContainer\NVDisplay.Container.exe: command succeeded with empty output
220126 09:46:32.665 le/profile:507 > WARN 034 profile: error while getting binary name for C:\Program Files\WindowsApps\MicrosoftWindows.Client.WebExperience_421.20050.505.0_x64__cw5n1h2txyewy\Dashboard\Widgets.exe: failed to get file properties of C:\Program Files\WindowsApps\MicrosoftWindows.Client.WebExperience_421.20050.505.0_x64__cw5n1h2txyewy\Dashboard\Widgets.exe: command succeeded with empty output
220126 09:48:47.594 CURRENT TIME
```

</details>

<details>
<summary>Goroutine Stack</summary>

```
goroutine profile: total 69
12 @ 0x101de1a 0x102de2f 0x13dab25 0x13db197 0x104fba1
#	0x13dab24	github.com/safing/portbase/api.(*DatabaseAPI).processSub+0x224	/home/user/git/safing/portbase/api/database.go:415
#	0x13db196	github.com/safing/portbase/api.(*DatabaseAPI).handleQsub+0x136	/home/user/git/safing/portbase/api/database.go:478

12 @ 0x101de1a 0x102de2f 0x16d0a0a 0x104fba1
#	0x16d0a09	github.com/xtaci/kcp-go/v5.(*TimedSched).sched+0x2c9	/home/user/go/pkg/mod/github.com/xtaci/kcp-go/v5@v5.6.1/timedsched.go:67

3 @ 0x101de1a 0x1013e65 0x1049365 0x108c30c 0x108d645 0x108e81f 0x1181dd6 0x1190e35 0x1289aff 0x121bb2a 0x121c885 0x121cadb 0x121f694 0x1285a71 0x1285aa0 0x128afe8 0x128f7e5 0x104fba1
#	0x1049364	internal/poll.runtime_pollWait+0x64		/usr/local/go/src/runtime/netpoll.go:222
#	0x108c30b	internal/poll.(*pollDesc).wait+0x4b		/usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#	0x108d644	internal/poll.execIO+0x104			/usr/local/go/src/internal/poll/fd_windows.go:175
#	0x108e81e	internal/poll.(*FD).Read+0x2fe			/usr/local/go/src/internal/poll/fd_windows.go:441
#	0x1181dd5	net.(*netFD).Read+0x55				/usr/local/go/src/net/fd_posix.go:55
#	0x1190e34	net.(*conn).Read+0x94				/usr/local/go/src/net/net.go:182
#	0x1289afe	net/http.(*connReader).Read+0x1be		/usr/local/go/src/net/http/server.go:798
#	0x121bb29	bufio.(*Reader).fill+0x109			/usr/local/go/src/bufio/bufio.go:101
#	0x121c884	bufio.(*Reader).ReadSlice+0x44			/usr/local/go/src/bufio/bufio.go:360
#	0x121cada	bufio.(*Reader).ReadLine+0x3a			/usr/local/go/src/bufio/bufio.go:389
#	0x121f693	net/textproto.(*Reader).readLineSlice+0x73	/usr/local/go/src/net/textproto/reader.go:58
#	0x1285a70	net/textproto.(*Reader).ReadLine+0xb0		/usr/local/go/src/net/textproto/reader.go:39
#	0x1285a9f	net/http.readRequest+0xdf			/usr/local/go/src/net/http/request.go:1012
#	0x128afe7	net/http.(*conn).readRequest+0x1a7		/usr/local/go/src/net/http/server.go:984
#	0x128f7e4	net/http.(*conn).serve+0x704			/usr/local/go/src/net/http/server.go:1851

2 @ 0x101de1a 0x1013e65 0x1049365 0x108c30c 0x108d645 0x108e81f 0x1181dd6 0x1190e35 0x121bb2a 0x121bcb6 0x13b52a7 0x13b782b 0x13b88fb 0x13b90b6 0x13d856a 0x139bd87 0x139b49e 0x139db85 0x104fba1
#	0x1049364	internal/poll.runtime_pollWait+0x64					/usr/local/go/src/runtime/netpoll.go:222
#	0x108c30b	internal/poll.(*pollDesc).wait+0x4b					/usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#	0x108d644	internal/poll.execIO+0x104						/usr/local/go/src/internal/poll/fd_windows.go:175
#	0x108e81e	internal/poll.(*FD).Read+0x2fe						/usr/local/go/src/internal/poll/fd_windows.go:441
#	0x1181dd5	net.(*netFD).Read+0x55							/usr/local/go/src/net/fd_posix.go:55
#	0x1190e34	net.(*conn).Read+0x94							/usr/local/go/src/net/net.go:182
#	0x121bb29	bufio.(*Reader).fill+0x109						/usr/local/go/src/bufio/bufio.go:101
#	0x121bcb5	bufio.(*Reader).Peek+0x55						/usr/local/go/src/bufio/bufio.go:139
#	0x13b52a6	github.com/gorilla/websocket.(*Conn).read+0x46				/home/user/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:370
#	0x13b782a	github.com/gorilla/websocket.(*Conn).advanceFrame+0x6a			/home/user/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:798
#	0x13b88fa	github.com/gorilla/websocket.(*Conn).NextReader+0x9a			/home/user/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:980
#	0x13b90b5	github.com/gorilla/websocket.(*Conn).ReadMessage+0x35			/home/user/go/pkg/mod/github.com/gorilla/websocket@v1.4.2/conn.go:1064
#	0x13d8569	github.com/safing/portbase/api.(*DatabaseAPI).handler+0x49		/home/user/git/safing/portbase/api/database.go:150
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b49d	github.com/safing/portbase/modules.(*Module).RunWorker+0x9d		/home/user/git/safing/portbase/modules/worker.go:47
#	0x139db84	github.com/safing/portbase/modules.(*Module).StartWorker.func1+0x64	/home/user/git/safing/portbase/modules/worker.go:27

2 @ 0x101de1a 0x102de2f 0x138df38 0x139bd87 0x139b7d1 0x104fba1
#	0x138df37	github.com/safing/portbase/database.(*Interface).DelayedCacheWriter+0x1d7	/home/user/git/safing/portbase/database/interface_cache.go:34
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6			/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130		/home/user/git/safing/portbase/modules/worker.go:78

2 @ 0x101de1a 0x102de2f 0x13a5925 0x139bd87 0x139b7d1 0x104fba1
#	0x13a5924	github.com/safing/portbase/rng.(*Feeder).run+0x2e4			/home/user/git/safing/portbase/rng/entropy.go:119
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130	/home/user/git/safing/portbase/modules/worker.go:78

2 @ 0x101de1a 0x102de2f 0x13d9045 0x139bd87 0x139b49e 0x139db85 0x104fba1
#	0x13d9044	github.com/safing/portbase/api.(*DatabaseAPI).writer+0x124		/home/user/git/safing/portbase/api/database.go:217
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b49d	github.com/safing/portbase/modules.(*Module).RunWorker+0x9d		/home/user/git/safing/portbase/modules/worker.go:47
#	0x139db84	github.com/safing/portbase/modules.(*Module).StartWorker.func1+0x64	/home/user/git/safing/portbase/modules/worker.go:27

2 @ 0x101de1a 0x102de2f 0x13dab25 0x13da732 0x104fba1
#	0x13dab24	github.com/safing/portbase/api.(*DatabaseAPI).processSub+0x224	/home/user/git/safing/portbase/api/database.go:415
#	0x13da731	github.com/safing/portbase/api.(*DatabaseAPI).handleSub+0xd1	/home/user/git/safing/portbase/api/database.go:387

1 @ 0x101de1a 0x1013e65 0x1049365 0x108c30c 0x108d645 0x108e81f 0x1181dd6 0x1190e35 0x128957f 0x104fba1
#	0x1049364	internal/poll.runtime_pollWait+0x64		/usr/local/go/src/runtime/netpoll.go:222
#	0x108c30b	internal/poll.(*pollDesc).wait+0x4b		/usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#	0x108d644	internal/poll.execIO+0x104			/usr/local/go/src/internal/poll/fd_windows.go:175
#	0x108e81e	internal/poll.(*FD).Read+0x2fe			/usr/local/go/src/internal/poll/fd_windows.go:441
#	0x1181dd5	net.(*netFD).Read+0x55				/usr/local/go/src/net/fd_posix.go:55
#	0x1190e34	net.(*conn).Read+0x94				/usr/local/go/src/net/net.go:182
#	0x128957e	net/http.(*connReader).backgroundRead+0x5e	/usr/local/go/src/net/http/server.go:690

1 @ 0x101de1a 0x1013e65 0x1049365 0x108c30c 0x108d645 0x108e81f 0x1181dd6 0x1190e35 0x15d4fb3 0x15e1711 0x139bd87 0x139b7d1 0x104fba1
#	0x1049364	internal/poll.runtime_pollWait+0x64					/usr/local/go/src/runtime/netpoll.go:222
#	0x108c30b	internal/poll.(*pollDesc).wait+0x4b					/usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#	0x108d644	internal/poll.execIO+0x104						/usr/local/go/src/internal/poll/fd_windows.go:175
#	0x108e81e	internal/poll.(*FD).Read+0x2fe						/usr/local/go/src/internal/poll/fd_windows.go:441
#	0x1181dd5	net.(*netFD).Read+0x55							/usr/local/go/src/net/fd_posix.go:55
#	0x1190e34	net.(*conn).Read+0x94							/usr/local/go/src/net/net.go:182
#	0x15d4fb2	github.com/safing/portmaster/resolver.listenForDNSPackets+0x92		/home/user/git/safing/portmaster/resolver/resolver-mdns.go:328
#	0x15e1710	github.com/safing/portmaster/resolver.listenToMDNS.func1+0x50		/home/user/git/safing/portmaster/resolver/resolver-mdns.go:86
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130	/home/user/git/safing/portbase/modules/worker.go:78

1 @ 0x101de1a 0x1013e65 0x1049365 0x108c30c 0x108d645 0x108e81f 0x1181dd6 0x1190e35 0x15d4fb3 0x15e1811 0x139bd87 0x139b7d1 0x104fba1
#	0x1049364	internal/poll.runtime_pollWait+0x64					/usr/local/go/src/runtime/netpoll.go:222
#	0x108c30b	internal/poll.(*pollDesc).wait+0x4b					/usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#	0x108d644	internal/poll.execIO+0x104						/usr/local/go/src/internal/poll/fd_windows.go:175
#	0x108e81e	internal/poll.(*FD).Read+0x2fe						/usr/local/go/src/internal/poll/fd_windows.go:441
#	0x1181dd5	net.(*netFD).Read+0x55							/usr/local/go/src/net/fd_posix.go:55
#	0x1190e34	net.(*conn).Read+0x94							/usr/local/go/src/net/net.go:182
#	0x15d4fb2	github.com/safing/portmaster/resolver.listenForDNSPackets+0x92		/home/user/git/safing/portmaster/resolver/resolver-mdns.go:328
#	0x15e1810	github.com/safing/portmaster/resolver.listenToMDNS.func3+0x50		/home/user/git/safing/portmaster/resolver/resolver-mdns.go:108
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130	/home/user/git/safing/portbase/modules/worker.go:78

1 @ 0x101de1a 0x1013e65 0x1049365 0x108c30c 0x108d645 0x108e81f 0x1181dd6 0x1190e35 0x15d4fb3 0x15e1891 0x139bd87 0x139b7d1 0x104fba1
#	0x1049364	internal/poll.runtime_pollWait+0x64					/usr/local/go/src/runtime/netpoll.go:222
#	0x108c30b	internal/poll.(*pollDesc).wait+0x4b					/usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#	0x108d644	internal/poll.execIO+0x104						/usr/local/go/src/internal/poll/fd_windows.go:175
#	0x108e81e	internal/poll.(*FD).Read+0x2fe						/usr/local/go/src/internal/poll/fd_windows.go:441
#	0x1181dd5	net.(*netFD).Read+0x55							/usr/local/go/src/net/fd_posix.go:55
#	0x1190e34	net.(*conn).Read+0x94							/usr/local/go/src/net/net.go:182
#	0x15d4fb2	github.com/safing/portmaster/resolver.listenForDNSPackets+0x92		/home/user/git/safing/portmaster/resolver/resolver-mdns.go:328
#	0x15e1890	github.com/safing/portmaster/resolver.listenToMDNS.func4+0x50		/home/user/git/safing/portmaster/resolver/resolver-mdns.go:119
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130	/home/user/git/safing/portbase/modules/worker.go:78

1 @ 0x101de1a 0x1013e65 0x1049365 0x108c30c 0x108d645 0x108f359 0x1181f05 0x119b425 0x1199b85 0x14420e5 0x142cf39 0x142a2ea 0x142bacf 0x142ab3a 0x174b565 0x139bd87 0x139b7d1 0x104fba1
#	0x1049364	internal/poll.runtime_pollWait+0x64					/usr/local/go/src/runtime/netpoll.go:222
#	0x108c30b	internal/poll.(*pollDesc).wait+0x4b					/usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#	0x108d644	internal/poll.execIO+0x104						/usr/local/go/src/internal/poll/fd_windows.go:175
#	0x108f358	internal/poll.(*FD).ReadFrom+0x118					/usr/local/go/src/internal/poll/fd_windows.go:581
#	0x1181f04	net.(*netFD).readFrom+0x64						/usr/local/go/src/net/fd_posix.go:61
#	0x119b424	net.(*UDPConn).readFrom+0x64						/usr/local/go/src/net/udpsock_posix.go:47
#	0x1199b84	net.(*UDPConn).ReadFrom+0x64						/usr/local/go/src/net/udpsock.go:118
#	0x14420e4	github.com/miekg/dns.ReadFromSessionUDP+0x64				/home/user/go/pkg/mod/github.com/miekg/dns@v1.1.44/udp_windows.go:19
#	0x142cf38	github.com/miekg/dns.(*Server).readUDP+0xd8				/home/user/go/pkg/mod/github.com/miekg/dns@v1.1.44/server.go:687
#	0x142a2e9	github.com/miekg/dns.defaultReader.ReadUDP+0x49				/home/user/go/pkg/mod/github.com/miekg/dns@v1.1.44/server.go:174
#	0x142bace	github.com/miekg/dns.(*Server).serveUDP+0x20e				/home/user/go/pkg/mod/github.com/miekg/dns@v1.1.44/server.go:501
#	0x142ab39	github.com/miekg/dns.(*Server).ListenAndServe+0x339			/home/user/go/pkg/mod/github.com/miekg/dns@v1.1.44/server.go:330
#	0x174b564	github.com/safing/portmaster/nameserver.startListener.func1+0x44	/home/user/git/safing/portmaster/nameserver/module.go:114
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130	/home/user/git/safing/portbase/modules/worker.go:78

1 @ 0x101de1a 0x1013e65 0x1049365 0x108c30c 0x108d645 0x1090c59 0x1090f0a 0x1183565 0x1198e59 0x119796b 0x1293dae 0x1293ade 0x13e3f14 0x139bd87 0x139b49e 0x13e1b36 0x104fba1
#	0x1049364	internal/poll.runtime_pollWait+0x64				/usr/local/go/src/runtime/netpoll.go:222
#	0x108c30b	internal/poll.(*pollDesc).wait+0x4b				/usr/local/go/src/internal/poll/fd_poll_runtime.go:87
#	0x108d644	internal/poll.execIO+0x104					/usr/local/go/src/internal/poll/fd_windows.go:175
#	0x1090c58	internal/poll.(*FD).acceptOne+0x98				/usr/local/go/src/internal/poll/fd_windows.go:810
#	0x1090f09	internal/poll.(*FD).Accept+0x169				/usr/local/go/src/internal/poll/fd_windows.go:844
#	0x1183564	net.(*netFD).accept+0x84					/usr/local/go/src/net/fd_windows.go:139
#	0x1198e58	net.(*TCPListener).accept+0x38					/usr/local/go/src/net/tcpsock_posix.go:139
#	0x119796a	net.(*TCPListener).Accept+0x6a					/usr/local/go/src/net/tcpsock.go:261
#	0x1293dad	net/http.(*Server).Serve+0x26d					/usr/local/go/src/net/http/server.go:2937
#	0x1293add	net/http.(*Server).ListenAndServe+0xbd				/usr/local/go/src/net/http/server.go:2866
#	0x13e3f13	github.com/safing/portbase/api.Serve.func1+0x33			/home/user/git/safing/portbase/api/router.go:63
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6	/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b49d	github.com/safing/portbase/modules.(*Module).RunWorker+0x9d	/home/user/git/safing/portbase/modules/worker.go:47
#	0x13e1b35	github.com/safing/portbase/api.Serve+0x1d5			/home/user/git/safing/portbase/api/router.go:62

1 @ 0x101de1a 0x102de2f 0x136bdb4 0x136b998 0x104fba1
#	0x136bdb3	github.com/safing/portbase/log.writer+0x3b3		/home/user/git/safing/portbase/log/output.go:156
#	0x136b997	github.com/safing/portbase/log.writerManager+0x97	/home/user/git/safing/portbase/log/output.go:113

1 @ 0x101de1a 0x102de2f 0x1394c98 0x104fba1
#	0x1394c97	github.com/safing/portbase/modules.microTaskScheduler+0x1b7	/home/user/git/safing/portbase/modules/microtasks.go:184

1 @ 0x101de1a 0x102de2f 0x139aee5 0x104fba1
#	0x139aee4	github.com/safing/portbase/modules.taskQueueHandler+0x1c4	/home/user/git/safing/portbase/modules/tasks.go:447

1 @ 0x101de1a 0x102de2f 0x139b1be 0x104fba1
#	0x139b1bd	github.com/safing/portbase/modules.taskScheduleHandler+0xfd	/home/user/git/safing/portbase/modules/tasks.go:497

1 @ 0x101de1a 0x102de2f 0x13a5c5d 0x139bd87 0x139b7d1 0x104fba1
#	0x13a5c5c	github.com/safing/portbase/rng.fullFeeder+0x15c				/home/user/git/safing/portbase/rng/fullfeed.go:25
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130	/home/user/git/safing/portbase/modules/worker.go:78

1 @ 0x101de1a 0x102de2f 0x13a66e5 0x139bd87 0x139b7d1 0x104fba1
#	0x13a66e4	github.com/safing/portbase/rng.osFeeder+0x1e4				/home/user/git/safing/portbase/rng/osfeeder.go:27
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130	/home/user/git/safing/portbase/modules/worker.go:78

1 @ 0x101de1a 0x102de2f 0x13a7014 0x139bd87 0x139b7d1 0x104fba1
#	0x13a7013	github.com/safing/portbase/rng.tickFeeder+0x253				/home/user/git/safing/portbase/rng/tickfeeder.go:60
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130	/home/user/git/safing/portbase/modules/worker.go:78

1 @ 0x101de1a 0x102de2f 0x13f45b8 0x174c090 0x101da49 0x104fba1
#	0x13f45b7	github.com/safing/portbase/run.Run+0x237	/home/user/git/safing/portbase/run/main.go:66
#	0x174c08f	main.main+0xcf					/home/user/git/safing/portmaster/cmds/portmaster-core/main.go:31
#	0x101da48	runtime.main+0x208				/usr/local/go/src/runtime/proc.go:204

1 @ 0x101de1a 0x102de2f 0x15534b5 0x139bd87 0x139b7d1 0x104fba1
#	0x15534b4	github.com/safing/portbase/notifications.cleaner+0x114			/home/user/git/safing/portbase/notifications/cleaner.go:13
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130	/home/user/git/safing/portbase/modules/worker.go:78

1 @ 0x101de1a 0x102de2f 0x1578398 0x139bd87 0x139b7d1 0x104fba1
#	0x1578397	github.com/safing/portmaster/intel/geoip.(*updateWorker).run+0x117	/home/user/git/safing/portmaster/intel/geoip/database.go:173
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130	/home/user/git/safing/portbase/modules/worker.go:78

1 @ 0x101de1a 0x102de2f 0x157ec65 0x139bd87 0x139b7d1 0x104fba1
#	0x157ec64	github.com/safing/portmaster/netenv.monitorNetworkChanges+0x164		/home/user/git/safing/portmaster/netenv/network-change.go:48
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130	/home/user/git/safing/portbase/modules/worker.go:78

1 @ 0x101de1a 0x102de2f 0x158017e 0x139bd87 0x139b7d1 0x104fba1
#	0x158017d	github.com/safing/portmaster/netenv.monitorOnlineStatus+0x13d		/home/user/git/safing/portmaster/netenv/online-status.go:357
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130	/home/user/git/safing/portbase/modules/worker.go:78

1 @ 0x101de1a 0x102de2f 0x159239c 0x139bd87 0x139b49e 0x139db85 0x104fba1
#	0x159239b	github.com/safing/portmaster/status.autoPilot+0xdb			/home/user/git/safing/portmaster/status/autopilot.go:16
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b49d	github.com/safing/portbase/modules.(*Module).RunWorker+0x9d		/home/user/git/safing/portbase/modules/worker.go:47
#	0x139db84	github.com/safing/portbase/modules.(*Module).StartWorker.func1+0x64	/home/user/git/safing/portbase/modules/worker.go:27

1 @ 0x101de1a 0x102de2f 0x15d31e5 0x15e1905 0x139bd87 0x139b7d1 0x104fba1
#	0x15d31e4	github.com/safing/portmaster/resolver.handleMDNSMessages+0x104		/home/user/git/safing/portmaster/resolver/resolver-mdns.go:137
#	0x15e1904	github.com/safing/portmaster/resolver.listenToMDNS.func5+0x44		/home/user/git/safing/portmaster/resolver/resolver-mdns.go:126
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130	/home/user/git/safing/portbase/modules/worker.go:78

1 @ 0x101de1a 0x102de2f 0x1635aa8 0x139bd87 0x139b7d1 0x104fba1
#	0x1635aa7	github.com/safing/portmaster/profile.cleanActiveProfiles+0x187		/home/user/git/safing/portmaster/profile/active.go:84
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130	/home/user/git/safing/portbase/modules/worker.go:78

1 @ 0x101de1a 0x102de2f 0x16421c8 0x139bd87 0x139b7d1 0x104fba1
#	0x16421c7	github.com/safing/portmaster/profile.startProfileUpdateChecker.func1+0x227	/home/user/git/safing/portmaster/profile/database.go:59
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6			/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130		/home/user/git/safing/portbase/modules/worker.go:78

1 @ 0x101de1a 0x102de2f 0x16d0f45 0x104fba1
#	0x16d0f44	github.com/xtaci/kcp-go/v5.(*TimedSched).prepend+0x284	/home/user/go/pkg/mod/github.com/xtaci/kcp-go/v5@v5.6.1/timedsched.go:103

1 @ 0x101de1a 0x102de2f 0x170f695 0x139bd87 0x139b7d1 0x104fba1
#	0x170f694	github.com/safing/portmaster/network.connectionCleaner+0x114		/home/user/git/safing/portmaster/network/clean.go:24
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130	/home/user/git/safing/portbase/modules/worker.go:78

1 @ 0x101de1a 0x102de2f 0x171455a 0x139bd87 0x139b7d1 0x104fba1
#	0x1714559	github.com/safing/portmaster/network.openDNSRequestWriter+0x119		/home/user/git/safing/portmaster/network/dns.go:91
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130	/home/user/git/safing/portbase/modules/worker.go:78

1 @ 0x101de1a 0x102de2f 0x173d8ac 0x139bd87 0x139b49e 0x139db85 0x104fba1
#	0x173d8ab	github.com/safing/portmaster/firewall.packetHandler+0x10b		/home/user/git/safing/portmaster/firewall/interception.go:522
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b49d	github.com/safing/portbase/modules.(*Module).RunWorker+0x9d		/home/user/git/safing/portbase/modules/worker.go:47
#	0x139db84	github.com/safing/portbase/modules.(*Module).StartWorker.func1+0x64	/home/user/git/safing/portbase/modules/worker.go:27

1 @ 0x101de1a 0x102de2f 0x173dba9 0x139bd87 0x139b49e 0x139db85 0x104fba1
#	0x173dba8	github.com/safing/portmaster/firewall.statLogger+0x248			/home/user/git/safing/portmaster/firewall/interception.go:536
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b49d	github.com/safing/portbase/modules.(*Module).RunWorker+0x9d		/home/user/git/safing/portbase/modules/worker.go:47
#	0x139db84	github.com/safing/portbase/modules.(*Module).StartWorker.func1+0x64	/home/user/git/safing/portbase/modules/worker.go:27

1 @ 0x101de1a 0xfe6ada 0xfe670b 0x15d2cec 0x139bd87 0x139b7d1 0x104fba1
#	0x15d2ceb	github.com/safing/portmaster/resolver.listenToMDNS+0x54b		/home/user/git/safing/portmaster/resolver/resolver-mdns.go:130
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b7d0	github.com/safing/portbase/modules.(*Module).runServiceWorker+0x130	/home/user/git/safing/portbase/modules/worker.go:78

1 @ 0x1048fa5 0x13ca0ca 0x13c9e67 0x13c6938 0x13d2fd6 0x162da73 0x13de3e4 0x13dd996 0x13e284f 0x13e3f8c 0x139bd87 0x139b49e 0x13e1c85 0x12939ea 0x128f98d 0x104fba1
#	0x1048fa4	runtime/pprof.runtime_goroutineProfileWithLabels+0x64			/usr/local/go/src/runtime/mprof.go:716
#	0x13ca0c9	runtime/pprof.writeRuntimeProfile+0xe9					/usr/local/go/src/runtime/pprof/pprof.go:724
#	0x13c9e66	runtime/pprof.writeGoroutine+0xa6					/usr/local/go/src/runtime/pprof/pprof.go:684
#	0x13c6937	runtime/pprof.(*Profile).WriteTo+0x3f7					/usr/local/go/src/runtime/pprof/pprof.go:331
#	0x13d2fd5	github.com/safing/portbase/utils/debug.(*Info).AddGoroutineStack+0x95	/home/user/git/safing/portbase/utils/debug/debug.go:132
#	0x162da72	github.com/safing/portmaster/core.debugInfo+0x112			/home/user/git/safing/portmaster/core/api.go:91
#	0x13de3e3	github.com/safing/portbase/api.(*Endpoint).ServeHTTP+0xa23		/home/user/git/safing/portbase/api/endpoints.go:438
#	0x13dd995	github.com/safing/portbase/api.(*endpointHandler).ServeHTTP+0xb5	/home/user/git/safing/portbase/api/endpoints.go:357
#	0x13e284e	github.com/safing/portbase/api.(*mainHandler).handle+0xbae		/home/user/git/safing/portbase/api/router.go:197
#	0x13e3f8b	github.com/safing/portbase/api.(*mainHandler).ServeHTTP.func1+0x4b	/home/user/git/safing/portbase/api/router.go:81
#	0x139bd86	github.com/safing/portbase/modules.(*Module).runWorker+0xa6		/home/user/git/safing/portbase/modules/worker.go:119
#	0x139b49d	github.com/safing/portbase/modules.(*Module).RunWorker+0x9d		/home/user/git/safing/portbase/modules/worker.go:47
#	0x13e1c84	github.com/safing/portbase/api.(*mainHandler).ServeHTTP+0xa4		/home/user/git/safing/portbase/api/router.go:80
#	0x12939e9	net/http.serverHandler.ServeHTTP+0xa9					/usr/local/go/src/net/http/server.go:2843
#	0x128f98c	net/http.(*conn).serve+0x8ac						/usr/local/go/src/net/http/server.go:1925

1 @ 0xfe4875 0x104c349 0x1344fba 0x172fd0f 0x172e931 0x104fba1
#	0x104c348	syscall.Syscall+0xe8									/usr/local/go/src/runtime/syscall_windows.go:188
#	0x1344fb9	golang.org/x/sys/windows.(*Proc).Call+0x139						/home/user/go/pkg/mod/golang.org/x/sys@v0.0.0-20211216021012-1d35b9e2eb4e/windows/dll_windows.go:170
#	0x172fd0e	github.com/safing/portmaster/firewall/interception/windowskext.RecvVerdictRequest+0x16e	/home/user/git/safing/portmaster/firewall/interception/windowskext/kext.go:167
#	0x172e930	github.com/safing/portmaster/firewall/interception/windowskext.Handler+0xb0		/home/user/git/safing/portmaster/firewall/interception/windowskext/handler.go:59

1 @ 0xfe4875 0x104c492 0x1068b65 0x10665ef 0x108e751 0x10963fe 0x10963d1 0x121de2b 0x13f48ac 0x104fba1
#	0x104c491	syscall.Syscall6+0xf1					/usr/local/go/src/runtime/syscall_windows.go:201
#	0x1068b64	syscall.ReadFile+0x104					/usr/local/go/src/syscall/zsyscall_windows.go:313
#	0x10665ee	syscall.Read+0x6e					/usr/local/go/src/syscall/syscall_windows.go:369
#	0x108e750	internal/poll.(*FD).Read+0x230				/usr/local/go/src/internal/poll/fd_windows.go:427
#	0x10963fd	os.(*File).read+0x7d					/usr/local/go/src/os/file_posix.go:31
#	0x10963d0	os.(*File).Read+0x50					/usr/local/go/src/os/file.go:116
#	0x121de2a	bufio.(*Scanner).Scan+0xaa				/usr/local/go/src/bufio/scan.go:214
#	0x13f48ab	github.com/safing/portbase/run.inputSignals+0x8b	/home/user/git/safing/portbase/run/main.go:116

1 @ 0xfed053 0x104b429 0x13f4029 0x104fba1
#	0x104b428	os/signal.signal_recv+0xa8	/usr/local/go/src/runtime/sigqueue.go:147
#	0x13f4028	os/signal.loop+0x28		/usr/local/go/src/os/signal/signal_unix.go:23


```

</details>

**Comment by dhaavi** [comment]
Hey @leochras,

You don't need to upgrade using winget, as the Portmaster updates itself.
The version you see here is the version of the installer, not the Portmaster itself.
(The installer version jumps to the current Portmaster version when updated to keep it easier.)

The things the installer does barely change, so you don't have to run it again.
Can winget just install the current package again in case this would become necessary?

**Comment by leochras** [comment]
Unless winget is provided a version number of the upgraded package, it will just keep upgrading on each `winget upgrade --all `is 
![image](https://user-images.githubusercontent.com/16163571/151342535-165a334d-23e5-47c4-9aa2-7875e0da43d6.png)

**Comment by dhaavi** [comment]
I see. While no damage can be done to the Portmaster this way, we should definitely avoid it.

Do you know which version number winget uses in this case?
I would expect winget to hold it's own index of installed packages and their versions.

We don't even use the "Safing.Portmaster" ID within the installer as far as I know.

The winget installer also in not managed by us, but by @OfficialEsco and others. (Thanks again!)
Maybe @OfficialEsco can also shed some light on this.

Extra note for @OfficialEsco here: we are currently testing a dependency of the Windows installer, so we would be shipping an updated installer in 2-4 weeks. That would be a perfect time to include fixes from this issue.

**Comment by OfficialEsco** [comment]
WinGet still uses `Safing.Portmaster`
Well, the fix to this issue is creating a DisplayVersion string at the uninstall registry under Installation / Update (`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Portmaster`)

However we've had this chat before, and this might actually be the only application i agree having no DisplayVersion makes sense because the installation is pretty much never being touched.
IF the upgrade progress is different from `0.7.0` to `0.8.0` ("major") than `0.7.0` to `0.7.1` (hotfix) you could create a DisplayVersion string at that time.

@leochras at this time these are your options
1. wait for https://github.com/microsoft/winget-cli/pull/1765
2. do your own Hotfix and create a DisplayVersion string in the registry

**Comment by dhaavi** [comment]
Thanks @OfficialEsco for chiming in here. Also, sorry @leochras, I didn't connect the dots before that you are now also involved with WinGet.

Thinking about this more, I think it does make sense to include the version number, as there will be some (even if very vew) updates in the future, that require re-running the installer - or are the cleanest solution, even if possible differently.

**Comment by leochras** [comment]
To be clear, I also think this is a problem with winget and not portmaster itself. Thank you both for your efforts!

**Comment by dhaavi** [comment]
Sorry, issue was closed by misconfigured bot.

**Comment by OfficialEsco** [comment]
Hey, have you given this some more thought?
I see 0.8.X is in stable, but still no DisplayVersion
IMO a simple fix would be to add
```
WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\Portmaster" \
		"DisplayVersion" "${PRODUCT_VERSION}"
```
to https://github.com/safing/portmaster-packaging/blob/4de0b78ad18b3c1c7db3036769454f4991efc86b/windows/portmaster-installer.nsi#L207

**Comment by dhaavi** [comment]
Thanks for the nudge - I've actually already done that with the latest version of the installer, but I had to withdraw that update again, as a dependency had a bug that prevented proper installation.
We've released the fix for that bug yesterday and will build new installers with that soon.

**Comment by dhaavi** [comment]
The Portmaster Windows Installer is now out with version v0.8.8.

Please check if the version number is recognized correctly.

**Comment by OfficialEsco** [comment]
He did a sneaky non-public release, but since he said 0.8.8 its https://updates.safing.io/windows_amd64/packages/portmaster-installer_v0-8-8.exe
The Signature date is 2022-06-02 and its still not fixed (=
![VirtualBoxVM_EOYOJg2qxZ](https://user-images.githubusercontent.com/15158490/171648569-a14b3aad-31d5-4138-803e-36f6c9af986f.png)

**Comment by leochras** [comment]
> He did a sneaky non-public release, but since he said 0.8.8 its https://updates.safing.io/windows_amd64/packages/portmaster-installer_v0-8-8.exe The Signature date is 2022-06-02 and its still not fixed (= ![VirtualBoxVM_EOYOJg2qxZ](https://user-images.githubusercontent.com/15158490/171648569-a14b3aad-31d5-4138-803e-36f6c9af986f.png)
> 
> edit: oh yeah https://updates.safing.io/latest/windows_amd64/packages/portmaster-installer.exe downloads 0.8.8 too

Okay, thank you for checking. 
![image](https://user-images.githubusercontent.com/16163571/171649194-85e31a53-32b0-4c59-8d18-38c469b0429a.png)

**Comment by dhaavi** [comment]
Oh, right, I forgot to tag the version, my bad. Did that now.

Hm. Bummer. I guess I'll have to look into it again.

**Comment by OfficialEsco** [comment]
OHHHHHHHHH I see what you have done https://github.com/safing/portmaster-packaging/commit/4de0b78ad18b3c1c7db3036769454f4991efc86b
This seems to only apply to the installer description
![explorer_GBhf9ztPOS](https://user-images.githubusercontent.com/15158490/171664715-d97f3573-b48c-4d4a-b521-6cf5aa23d7a5.png)
which then means https://github.com/safing/portmaster/issues/503#issuecomment-1098377834 is still the solution

**Comment by dhaavi** [comment]
Thanks again for the PR, @OfficialEsco, it is now released as version [v0.8.8.1](https://github.com/safing/portmaster-packaging/releases/tag/v0.8.8.1).

It worked for me, but would be nice to get confirmation from you two!

**Comment by OfficialEsco** [comment]
Already confirmed it works =)
However i cannot find the direct download url since https://updates.safing.io/windows_amd64/packages/portmaster-installer_v0-8-8-1.exe returns `404 Not Found`

Update while typing: apparently https://updates.safing.io/windows_amd64/packages/portmaster-installer_v0-8-8.exe downloads 0.8.8.1

I'm guessing in the future you will build the installer and release it on GitHub, however until then could you include a direct download link to the installer in the release notes?

However since you added the FileVersion and ProductVersion we could move over to https://updates.safing.io/latest/windows_amd64/packages/portmaster-installer.exe since IIRC all the installer just downloads the latest version anyways? (I would probably recommend you to add something to stop it from doing that as Privacy people can be.. difficult)
